# SConstruct file for a sample ARP listener

env = Environment()
env["CXXFLAGS"] = "-Wall -g -ggdb"
env["LIBS"] = Split("cyanid net pcap")
env["CPPPATH"] = Split("/usr/include/cyanid")

sources = Split("main.cpp listener.cpp")
env.Program('arp_listener', sources)
